name: Build app
description: Builds app

inputs:
  working-directory:
    description: "Optional input to set working directory"
    required: false
    default: ./nvsc-lpl-app

outputs:
  distribution-directory:
    description: "Distribution directory"
    value: ${{ inputs.working-directory }}/dist

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: npm run build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
