name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions: { }

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment and install dependencies
        uses: ./.github/actions/prepare-vite-environment

      - name: Build
        run: npm run build
        working-directory: nvsc-lpl-app
