name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy page
    runs-on: ubuntu-latest
    concurrency: deploy-github-page
    timeout-minutes: 10
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build app
        id: app
        uses: ./.github/actions/build-vite-app

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ steps.app.outputs.distribution-directory }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
